Travis CI
Genetic-Strictness/Autobahn pull request #19
Opened 2016-10-03 19:02 UTC by cronburg

See commit message for details.

This should be merged after #13 and #17.

2016-10-03 19:08 UTC, dnunez02 commented on .gitignore
> +/.stack-work
This is meant to be .stack-work?

2016-10-03 19:08 UTC, dnunez02 commented on .gitignore
> +/stack.yaml
Ditto.

2016-10-03 19:11 UTC, dnunez02 commented on README.md
> +WARNING: Autobahn will overwrite the original source of your project. You should
We should fix this instead of leaving a WARNING.

2016-10-03 19:19 UTC, dnunez02 commented on src/Main.hs
> +fitness cfg reps files bangVecs = do
Good call replacing most of the args with Cfg.

Add the type of this function.

2016-10-03 19:26 UTC, dnunez02 requested changes
Needs another once over for small things. But it looks good.

2016-10-04 16:40 UTC, cronburg commented on README.md
> +WARNING: Autobahn will overwrite the original source of your project. You should
Making an issue now.

2016-10-04 17:08 UTC, merged